name: Maven Site

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  site:
    name: site
    uses: rose-group/.github/.github/workflows/site.yml@main
    secrets: inherit
    with:
      multi_modules: true
